services:
  backend:
    build: .
    container_name: collegehop-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: college_hop
      DB_PASSWORD: college_hop
      DB_NAME: college_hop
      UPLOAD_DIR: /app/uploads
      UPLOAD_BASE_URL: http://localhost:8080/uploads
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:15
    container_name: collegehop-postgres
    environment:
      POSTGRES_USER: college_hop
      POSTGRES_PASSWORD: college_hop
      POSTGRES_DB: college_hop
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
